### ISSUE TITLE
Having problem to push data

### ISSUE THREAD

**Issue by azharmalik3** [runtastic/newrelic-elixir#1]
Hi,

I have configured newrelic-elixir and configured and running but give an error when pushing data.

Here is error details:

```
[error] NewRelic.Poller: push failed: %CaseClauseError{term: {:error, {{:noproc, {:gen_server, :call, [:undefined, {:socket, #PID<0.664.0>, 'collector.newrelic.com', 443, true}, :infinity]}}, [{:lhttpc_manager, :ensure_call, 6, [file: '/home/azhar/evercam/evercam-media/deps/lhttpc/src/lhttpc_manager.erl', line: 236]}, {:lhttpc_client, :execute, 9, [file: '/home/azhar/evercam/evercam-media/deps/lhttpc/src/lhttpc_client.erl', line: 145]}, {:lhttpc_client, :request, 9, [file: '/home/azhar/evercam/evercam-media/deps/lhttpc/src/lhttpc_client.erl', line: 93]}]}}}
```

Please help me to solve this issue.

**Comment by andreaseger** [comment]
Hi,
thanks for trying our library. Unfortunately it's in a very early stage and we currently halted further development.
Right now I would recommend using one of the other mentioned packages ( e.g. https://github.com/romul/newrelic.ex ) instead as although we got a working prototype running most of the code is untested and due to internal refocusing we did not yet have the time to continue developing this library further.

I will make sure to state this more clearly in the readme.
